CREATE TABLE IF NOT EXISTS grado_educacion (
  id VARCHAR(100) PRIMARY KEY DEFAULT (UUID()),
  nombre VARCHAR(150) NOT NULL UNIQUE,
  orden INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
