CREATE TABLE IF NOT EXISTS estudiante (
  id_estudiante VARCHAR(100) PRIMARY KEY DEFAULT (UUID()),
  id_usuario VARCHAR(100) NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  edad INT NOT NULL,
  sexo VARCHAR(20) NOT NULL,
  municipio_nacimiento VARCHAR(150) NOT NULL,
  departamento_nacimiento VARCHAR(150) NOT NULL,
  pais_nacimiento VARCHAR(150) NOT NULL,
  religion VARCHAR(150) NOT NULL,
  direccion_actual VARCHAR(255) NOT NULL,
  barrio_vereda_actual VARCHAR(255) NOT NULL,
  ciudad_actual VARCHAR(150) NOT NULL,
  departamento_actual VARCHAR(150) NOT NULL,
  pais_actual VARCHAR(150) NOT NULL,
  file_foto VARCHAR(255) NOT NULL,
  file_doc VARCHAR(255) NOT NULL,
  file_diagnostico VARCHAR(255),
  ref1_nombres VARCHAR(150) NOT NULL,
  ref1_apellidos VARCHAR(150) NOT NULL,
  ref1_tel VARCHAR(50) NOT NULL,
  ref2_nombres VARCHAR(150) NOT NULL,
  ref2_apellidos VARCHAR(150) NOT NULL,
  ref2_tel VARCHAR(50) NOT NULL,
  ref3_nombres VARCHAR(150) NOT NULL,
  ref3_apellidos VARCHAR(150) NOT NULL,
  ref3_tel VARCHAR(50) NOT NULL,
  ref4_nombres VARCHAR(150) NOT NULL,
  ref4_apellidos VARCHAR(150) NOT NULL,
  ref4_tel VARCHAR(50) NOT NULL,
  ref5_nombres VARCHAR(150) NOT NULL,
  ref5_apellidos VARCHAR(150) NOT NULL,
  ref5_tel VARCHAR(50) NOT NULL,
  ref6_nombres VARCHAR(150) NOT NULL,
  ref6_apellidos VARCHAR(150) NOT NULL,
  ref6_tel VARCHAR(50) NOT NULL,
  limitaciones VARCHAR(255),
  otras_limitaciones VARCHAR(255),
  capacidades VARCHAR(255),
  ci_puntaje DECIMAL(6,2),
  padre_apellido1 VARCHAR(150) NOT NULL,
  padre_apellido2 VARCHAR(150) NOT NULL,
  padre_nombre VARCHAR(150) NOT NULL,
  padre_cedula VARCHAR(100) NOT NULL,
  padre_contacto1 VARCHAR(50) NOT NULL,
  padre_contacto2 VARCHAR(50),
  padre_file VARCHAR(255) NOT NULL,
  madre_apellido1 VARCHAR(150) NOT NULL,
  madre_apellido2 VARCHAR(150) NOT NULL,
  madre_nombre VARCHAR(150) NOT NULL,
  madre_cedula VARCHAR(100) NOT NULL,
  madre_contacto1 VARCHAR(50) NOT NULL,
  madre_contacto2 VARCHAR(50),
  madre_file VARCHAR(255) NOT NULL,
  acudiente_apellido1 VARCHAR(150) NOT NULL,
  acudiente_apellido2 VARCHAR(150) NOT NULL,
  acudiente_nombre VARCHAR(150) NOT NULL,
  acudiente_cedula VARCHAR(100) NOT NULL,
  acudiente_contacto1 VARCHAR(50) NOT NULL,
  acudiente_contacto2 VARCHAR(50),
  acudiente_file VARCHAR(255) NOT NULL,
  problemasalud VARCHAR(255),
  eps VARCHAR(150) NOT NULL,
  ips VARCHAR(150) NOT NULL,
  rh VARCHAR(10) NOT NULL,
  observaciones TEXT,
  CONSTRAINT fk_estudiante_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
