-- Migration: 014_create_materia.sql
CREATE TABLE IF NOT EXISTS materia (
  id VARCHAR(100) PRIMARY KEY DEFAULT (UUID()),
  nombre VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
