CREATE TABLE IF NOT EXISTS auditoria_pago (
  id VARCHAR(100) PRIMARY KEY DEFAULT (UUID()),
  id_pago VARCHAR(100) UNIQUE NOT NULL,
  nombres VARCHAR(150) NOT NULL,
  apellido1 VARCHAR(100) NOT NULL,
  apellido2 VARCHAR(100) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ap_pago FOREIGN KEY (id_pago) REFERENCES pago(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
