import { z } from 'zod';

export const datosMatriculaSchema = z.object({
    // id_usuario se generará en el backend; recibimos datos del estudiante desde el formulario
    nombres: z.string().min(1, 'nombres es requerido'),
    apellido1: z.string().min(1, 'primer apellido es requerido'),
    apellido2: z.string().min(1, 'segundo apellido es requerido'),
    contacto1: z.string().min(1, 'contacto 1 es requerido'),
    contacto2: z.string().optional().nullable(),
    email: z.string().min(1, 'email es requerido'),
    id_tipo_documento: z.string().min(1, 'el tipo de documento es requerido'),
    no_documento: z.string().min(1, 'numero de documento es requerido'),
    fecha_expedicion_documento: z.string().min(1, 'la fecha de expedicion del documento es requerida'),
    fecha_nacimiento: z.string().min(1, 'fecha de nacimiento es requerida'),
    edad: z.string().min(1, 'edad es requerida'),
    sexo: z.string().min(1, 'sexo es requerido'),
    municipio_nacimiento: z.string().min(1, 'municipio de nacimiento es requerido'),
    departamento_nacimiento: z.string().min(1, 'departamento de nacimiento es requerido'),
    pais_nacimiento: z.string().min(1, 'país de nacimiento es requerido'),
    religion: z.string().min(1, 'religión es requerida'),
    barrio_vereda_actual: z.string().min(1, 'barrio o vereda actual es requerido'),
    ciudad_actual: z.string().min(1, 'ciudad actual es requerida'),
    departamento_actual: z.string().min(1, 'departamento actual es requerido'),
    pais_actual: z.string().min(1, 'país actual es requerido'),
    file_doc: z.string().min(1, 'documento de identidad es requerido'),
    file_foto: z.string().min(1, 'foto es requerida'),
    id_tipo_estudio: z.string().min(1, 'id de tipo estudio es requerido'),
    id_grado_educacion: z.array(z.string().min(1)).nonempty('Se requiere al menos un id_grado_educacion'),
    id_tiempo_validacion: z.string().optional().nullable(),
    file_certificado_grados: z.string().min(1, 'certificado de grados es requerido'),
    limitaciones: z.array(z.string()).optional(),
    otras_limitaciones: z.string().optional(),
    file_diagnostico: z.string().optional(),
    capacidades: z.array(z.string()).optional(),
    ci_puntaje: z.string().min(1, 'puntaje del CI es requerido'),
    problemasalud: z.string().optional().nullable(),
    eps: z.string().optional().nullable(),
    ips: z.string().optional().nullable(),
    rh: z.string().optional().nullable(),
    observaciones: z.string().optional().nullable(),
    file_compromiso: z.string().min(1, 'compromiso es requerido'),
    file_comprobante_pago: z.string().min(1, 'comprobante de pago es requerido'),
    padre_apellido1: z.string().min(1, 'primer apellido del padre es requerido'),
    padre_apellido2: z.string().min(1, 'segundo apellido del padre es requerido'),
    padre_nombre: z.string().min(1, 'nombre del padre es requerido'),
    padre_cedula: z.string().min(1, 'cédula del padre es requerida'),
    padre_file: z.string().min(1, 'archivo del padre es requerido'),
    padre_contacto1: z.string().min(1, 'contacto 1 del padre es requerido'),
    padre_contacto2: z.string().optional().nullable(),
    madre_apellido1: z.string().min(1, 'primer apellido de la madre es requerido'),
    madre_apellido2: z.string().min(1, 'segundo apellido de la madre es requerido'),
    madre_nombre: z.string().min(1, 'nombre de la madre es requerido'),
    madre_cedula: z.string().min(1, 'cédula de la madre es requerida'),
    madre_file: z.string().min(1, 'archivo de la madre es requerido'),
    madre_contacto1: z.string().min(1, 'contacto 1 de la madre es requerido'),
    madre_contacto2: z.string().optional().nullable(),
    acudiente_apellido1: z.string().min(1, 'primer apellido del acudiente es requerido'),
    acudiente_apellido2: z.string().min(1, 'segundo apellido del acudiente es requerido'),
    acudiente_nombre: z.string().min(1, 'nombre del acudiente es requerido'),
    acudiente_cedula: z.string().min(1, 'cédula del acudiente es requerida'),
    acudiente_file: z.string().min(1, 'archivo del acudiente es requerido'),
    acudiente_contacto1: z.string().min(1, 'contacto 1 del acudiente es requerido'),
    acudiente_contacto2: z.string().optional().nullable(),
    ref1_nombres: z.string().min(1, 'nombres de la referencia 1 es requerido'),
    ref1_apellidos: z.string().min(1, 'apellidos de la referencia 1 es requerido'),
    ref1_tel: z.string().min(1, 'teléfono de la referencia 1 es requerido'),
    ref2_nombres: z.string().min(1, 'nombres de la referencia 2 es requerido'),
    ref2_apellidos: z.string().min(1, 'apellidos de la referencia 2 es requerido'),
    ref2_tel: z.string().min(1, 'teléfono de la referencia 2 es requerido'),
    ref3_nombres: z.string().min(1, 'nombres de la referencia 3 es requerido'),
    ref3_apellidos: z.string().min(1, 'apellidos de la referencia 3 es requerido'),
    ref3_tel: z.string().min(1, 'teléfono de la referencia 3 es requerido'),
    ref4_nombres: z.string().min(1, 'nombres de la referencia 4 es requerido'),
    ref4_apellidos: z.string().min(1, 'apellidos de la referencia 4 es requerido'),
    ref4_tel: z.string().min(1, 'teléfono de la referencia 4 es requerido'),
    ref5_nombres: z.string().min(1, 'nombres de la referencia 5 es requerido'),
    ref5_apellidos: z.string().min(1, 'apellidos de la referencia 5 es requerido'),
    ref5_tel: z.string().min(1, 'teléfono de la referencia 5 es requerido'),
    ref6_nombres: z.string().min(1, 'nombres de la referencia 6 es requerido'),
    ref6_apellidos: z.string().min(1, 'apellidos de la referencia 6 es requerido'),
    ref6_tel: z.string().min(1, 'teléfono de la referencia 6 es requerido'),
    id_rol: z.string().min(1, 'id rol es requerido'),
    id_usuario: z.string().min(1, 'id usuario es requerido')
});

export type DatosMatricula = z.infer<typeof datosMatriculaSchema>

export const formularioMatriculaSchema = datosMatriculaSchema.omit({
    id_rol: true,
    id_usuario: true,
});

export type FormularioMatriculaSchema = z.infer<typeof formularioMatriculaSchema>;
