-- Seed: 105_seed_rubro.sql
INSERT IGNORE INTO rubro (nombre, descripcion, monto_base) VALUES
  ('Matricula', 'Pago matrícula', 230000),
  ('Mensualidad 1° a 5°', 'Pago mensual de matrícula de 1° a 5°', 117000),
  ('Mensualidad 6° a 8°', 'Pago mensual de matrícula de 6° a 8°', 122000),
  ('Mensualidad 9°', 'Pago mensual de matrícula de 9°', 132000),
  ('Mensualidad 10° a 11°', 'Pago mensual de matrícula de 10° a 11°', 167000),
  ('Nivelación', 'Pago por nivelación académica', 95000),
  ('Boletín', 'Boletín académico de notas', 80000),
  ('Recargos', 'Recargos por retraso en el pago despues del 10 de cada mes', 10500),
  ('Reingreso', 'Pago por reingreso por ser retirado por incumplimiento de los pagos', 10500),
  ('Constancia de estudio', 'Constancia académica de estudio', 42000),
  ('Certificado de notas para promoción (Fisico)', 'Certificado de notas Físico', 120000),
  ('Certificado de notas para promoción (Digital)', 'Certificado de notas Digital', 100000),
  ('Validacion Primaria', 'Matricula Validación Primaria', 100000),
  ('Hoja de vida del SIMAT', 'aplica para estudiantes que no han sido escolarizados', 32000),
  ('Rubros extranjeros', 'Valor para alumnos extranjeros', 411000),
  ('Medía técnica con enfasis comercial', 'Pago por media técnica con enfasis comercial', 300000),
  ('Inscripción al ICFES', 'Inscripción al ICFES', 170000),
  ('Curso Pre-ICFES', 'Curso capacitación Pre-ICFES', 800000),
  ('Promoción anticipada', 'Promoción anticipada', 180000),
  ('Certificación de grado', 'Certificación de grado', 0),
  ('Derechos de grado', 'Derechos de grado', 450000),
  ('Derechos de grado preescolar, 5° y 9°', 'Derechos de grado preescolar, 5° y 9°', 100000);
