-- Seed: 107_seed_materia.sql
INSERT IGNORE INTO materia (nombre, abreviatura) VALUES
  ('Ciencias Naturales/Ed.Ambiental Y Biología', 'CN'),
  ('Ciencias Sociales', 'CS'),
  ('Ed. Artística', 'EDU.ART'),
  ('Etica Y Valores', 'E & V'),
  ('Religión', 'RE'),
  ('Lengua Castellana', 'LC'),
  ('Matemáticas', 'MAT'),
  ('Dimension Corporal', 'D.COR'),
  ('Emprendimiento', 'EMP'),
  ('Convivencia', 'CONV'),
  ('Tecnologia E Informatica', 'TEC'),
  ('Idioma Extrajero (Inglés)', 'ING'),
  ('Ed. Física/ Recreación Y Deporte', 'EDU.FIS'),
  ('Dimension Estetica', 'D.EST'),
  ('Dimension Etica Y Valores', 'D.E & V'),
  ('Dimension Cognitiva', 'D.COG'),
  ('Dimension Comunicativa', 'D.COM'),
  ('Bachiller Comercial con enfasis en emprendimiento', 'B.COM');
